# Generated by Django 4.0.1 on 2022-04-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
